### ISSUE TITLE
CMA-ES with O(N)

### ISSUE THREAD

**Issue by ErnstTmp** [hardmaru/estool#1]
Hello Hardmaru,
thank you very much for you great blog and for publishing the code!!! I love it!
 Just a question - you mention that there is an CMA-ES scaling with O(N). We would love to use CMA-ES on larger problems.  Do you happen to know a paper on that?

Thanks and kind regards,
Ernst

**Comment by hardmaru** [comment]
Hi Ernst,

Check out [this](https://github.com/CMA-ES/pycma/issues/21) thread. The author of CMA-ES published a new recent technique for O(N) and implemented it in pycma. I had mix results w/ it but it seems they have resolved the performance issues now.

Regards.

**Comment by ErnstTmp** [comment]
Hi hardmaru,
thanks a lot for your fast response, this is great!
Kind regards
Ernst
