### ISSUE TITLE
[Weight decay] Should weight decay of model parameters instead ? 

### ISSUE THREAD

**Issue by zuoxingdong** [hardmaru/estool#15]
It seems the [current implementation](https://github.com/hardmaru/estool/blob/master/es.py#L117-L118) does weight decay on the fitness value, I am wondering if it should be performed on model parameters  ?
i.e.
```
if self.weight_decay > 0:
      l2_decay = compute_weight_decay(self.weight_decay, self.solutions)
      reward_table += l2_decay
```
the last line change to 
```
self.solutions += l2_decay
```

And if it is the case that weight decay performing on model parameters, should it be after the results to be computed for current iteration ? (e.g. in tell() of OpenES, now is `weight decay -> get current best param`, should it be opposite order, `get current best param -> weight decay` )

**Comment by hardmaru** [comment]
Hi @zuoxingdong ,

self.solutions are the model parameters, so I wouldn't want to add the l2_decay (which is in units of reward) to it.

**Comment by zuoxingdong** [comment]
@hardmaru Thanks for the reply, if I got it correctly, the reason why we can add L2 norm of model parameters to fitness value is that our original objective function is `E[F(theta)]`, which can be derived by REINFORCE-style under Gaussian assumption of population. The decay part is that `F` can be replaced by a new objective, i.e. `new_F = F - L2 decay part` because we want to maximize the fitness and at the same time to keep model parameters small. Is that right ?

**Comment by hardmaru** [comment]
Yup, I want to optimize for new_F. But keeping the original F for record keeping-
