### ISSUE TITLE
Can't run pre-trained biped models

### ISSUE THREAD

**Issue by ntduong** [hardmaru/estool#17]
Hi, first of all, thanks for making this great tool! 

I've tried a couple of pre-trained models, e.g., bullet_ant, bullet_kuka_grasping, and they all work fine. But I couldn't run the zoo `biped` models (same for `bipedhard`, `bipedhard_stoc`) with this command:
`python model.py biped zoo/biped.cma.1.96.best.json`.
It failed with the `NotImplementedError`, full trace below:

`Traceback (most recent call last):
  File "model.py", line 340, in <module>
    main()
  File "model.py", line 335, in main
    train_mode=False, render_mode=render_mode, num_episode=1)
  File "model.py", line 240, in simulate
    model.env.render("human")
  File "/Users/duongnt/tensorflow/lib/python3.6/site-packages/gym/core.py", line 110, in render
    raise NotImplementedError
NotImplementedError`

I already installed required dependencies gym, box2d, pybullet and mpi4py. Am I missing something?

**Comment by ctallec** [comment]
I had a similar issue when launching training. NotImplementedError errors were raised when reaching the first call to step. I fixed that by changing methods names _step to step and _render to render in box2d.biped. My guess is that it is related to a recent update of gym, but I'm not quite sure. Tell me if that helps.

**Comment by ntduong** [comment]
Thank you very much, @ctallec! Renaming underscored method names works.

According to the [gym release v0.9.6](https://github.com/openai/gym/releases/tag/v0.9.6), Env and Wrapper subclasses should define `step`, `reset`, `render`, `close`, `seed` rather than underscored method names.

I close this issue now. Perhaps, the box2d/biped.py code should be updated or the naming issue should probably be mentioned in the doc.
