### ISSUE TITLE
No colour

### ISSUE THREAD

**Issue by Davincb** [hardmaru/estool#18]
![screen shot 2018-10-21 at 02 12 37](https://user-images.githubusercontent.com/26183192/47262146-504c4400-d4d8-11e8-9dd7-1ac8243372f1.png)

Hi, thanks for this. I installed everything correctly and I can only get the opengl window to visualise the robot by pressing "w". There are no coloured simulations. 

I'm on OS high sierra, pyenv with 3.5.2, gym 0.9.1, latest bullet3 and pybullet. Has anyone seen this before (could be something simple)

**Comment by hardmaru** [comment]
I’ve last tried on an older pybullet circa 1.6.x can u see if that works?
(Haven’t had time to update for newer versions yet)
