### ISSUE TITLE
Bug in train.py

### ISSUE THREAD

**Issue by AliBaheri** [hardmaru/estool#19]
Hi,
I faced with the following error and similar to [https://github.com/hardmaru/estool/issues/8]

`File "/usr/lib/python3.6/subprocess.py", line 291, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['mpirun', '-np', '2', '/home/baheri/.virtualenvs/worldmodels/bin/python', '-u', '05_train_controller.py', 'car_racing', '--num_worker', '1', '--num_worker_trial', '2', '--num_episode', '4', '--max_length', '1000', '--eval_steps', '25']' returned non-zero exit status 1.`

The suggestion at that post did not help me. Any other suggestion to solve this issue?

**Comment by lynnezixuan** [comment]
Please try conda install mpi4py. It works for me.
