### ISSUE TITLE
The pre-trained Kuka model did not work

### ISSUE THREAD

**Issue by lynnezixuan** [hardmaru/estool#20]
I tried the pre-trained Kuka model in ./Zoo, but it can not grasp an object. Does anyone know the reason?

**Comment by hardmaru** [comment]
Which version of pybullet are u using?

When I trained the demo a long time ago I think it was pybullet v 1.6

**Comment by lynnezixuan** [comment]
Thank you, pybullet v1.6 works well. I tried it with the newest version (9000 iterations), and it cannot work.
