### ISSUE TITLE
Training time for BipedalWalkerHardcore-v2

### ISSUE THREAD

**Issue by dgriff777** [hardmaru/estool#3]
First off, terrific work on repo and blog post, very detailed and clear. 

I was able to solve the BipedalWalkerHardcore-v2, average 300+ for 100eps, with rl with an a3c implentation I made but it took quite a while train, unlike for BipedalWalker-v2 which took 5-10minutes, it took nearly two full days of training. I think mainly due to how fast it wanted to run to the finish but eventually learned some impressive moves. Did you experience a long training time using es as well?

Look forward to experimenting with your estool as final performance and robustness are most important in my use cases. Great work and thanks for creating!

**Comment by MaxwellRebo** [comment]
Were you using MPI or any other parallelization?

**Comment by hardmaru** [comment]
Hi @dgriff777, it's great to know that you can solve BipedalWalkerHardcore-v2 in 2 days using a3c. Your [rl_a3c_pytorch](https://github.com/dgriff777/rl_a3c_pytorch) is a really nice piece of work. Did you use the same A3C LSTM for the Bipedal Walker? I'm curious as to how to make A3C work well for continuous action spaces.

With my current setup it takes CMA-ES around a week to find the solution, with a feed forward network. I might try to use ES to solve the weights of an RNN or LSTM network later on to see if it helps. The disadvantage of using ES compared to A3C is that ES only knows the final cumulative reward at each episode. I think for this task, having access to the reward signal reward at every time step will be very useful, so I've been trying to solve the task (unsuccessfully) using PPO, and it's great to know that you are able to solve it with A3C.

Let me know if you manage to put out your A3C solution on a GitHub repo later on. Would be interested to studying how it works.

**Comment by dgriff777** [comment]
Hi @hardmaru, yeah it was adapted from that repo so used same framework. I kept the actor and critic network as one network as well. Unlike with the regular Bipedal worker where I used just used linear layers and lstm cell. For hardcore I stacked four frames of observations and used conv2d layers followed by an lstm cell than by three separate linear layers for value, mean and std dv. For conv2d layers they were all followed with leaky relu activations and used a softsign activation on the mean output and a softplus activation on the std dv output. It was trained with 48 worker agents as well. I also did not normalize observations or rewards but did clip rewards between the range [-1,1].

I wasn't planning to put a repo up showing the solution to be honest but maybe I will eventually. I'm interested to look how to integrate rl and es techniques for even more robust and flexible solution as there are weaknesses to rl that instead of being managed or mitigated could be more directly addressed.

**Comment by MultiPath** [comment]
Hi, thank you very much for your great work! Could I ask how many workers are you using on this?
Based on your comments,

"With my current setup, it takes CMA-ES around a week to find the solution, with a feed forward network. "

What's the running command?
Thank you so much for your kind attention

**Comment by hardmaru** [comment]
Hi!

This command should work (leaving other params as default)

```
python train.py bipedhard -e 16 -n 64 -t 4
```

Before you run this command, set `orig_mode` to `False` in `model.py`. I find the original reward function with the -100 penalty was there to favour RL style algorithms to learn not to fall, but for ES where I only care about the terminal reward, taking that out (for training only) produced better results. Evaluation will include the original reward.

It took a long time to train though, slightly more than a week, on a 64-core GCP machine.

I suggest you try the setup I described on the normal bipedal task first (to make sure everything flows smoothly), by defining the easier task in `config.py`:

```
bipedeasy = Game(env_name='BipedalWalker-v2',
  input_size=24,
  output_size=4,
  time_factor=0,
  layers=[40, 40],
  activation='tanh',
  noise_bias=0.0,
  output_noise=[False, False, False],
)
games['bipedeasy'] = bipedeasy
```

And try to train the `bipedeasy` first to make sure you can load the saved agents, etc., before spending time and valuable compute resources on `bipedhard`.

```
python train.py bipedeasy -e 16 -n 64 -t 4
```

Good luck!

**Comment by hardmaru** [comment]
These are some great insights you shared @dgriff777 thanks!

I'm also a bit disappointed that ES took so long to train BipedWalkerHardcore-v2. IMO this might even be more challenging than the Humanoid Mujoco-style tasks.

Working on ways to fuse ES and A3C will really push things forward I think. ES has the advantage of finding policies only using terminal reward, while A3C requires a nice hand-engineered reward signal, so it will be interesting to combine these approaches to come up with something really awesome and useful.

**Comment by dgriff777** [comment]
Thanks @hardmaru 

Its definitely a challenging environment for many reasons which I won't list cause I'm sure you aware of them.

The idea of combining ES and RL techniques is particularly intriguing. If you think of ES and its trained model as a model where the trained model/agent is model born with parameters(its attributes) that make it successful, i.e a natural or more appropriately the agent won the genetic lottery. Now with RL the trained agent is one that with attributes it has worked really hard gaining experience and learning from it (represented in its parameters) to be as successful it can be. So you got an agent born to perform exceptionally and an agent that has learned to perform exceptionally with what it has through experience. If you combine these two agents its not hard to see how this could be a powerful combination. Its definitely an intriguing idea to play around with for me.

Obviously how to design such a combo model in an efficient manner to make it computationally viable with todays resources is where the real challenge would be and better determining the possible potential of such a path.

**Comment by dgriff777** [comment]
Hey @hardmaru got the repo up for A3C solution! Trained again but normalized observations with a max-min normalization where last time I did no observation preprocessing. Was able to train in just over 24hrs with 64 threads on a 72 cpu AWS EC2. Just an initial commit needs some polishing though

**Comment by hardmaru** [comment]
Hey @dgriff777 sorry for the reply. Just saw your message!
Thanks for creating the repo for your solution. It looks really nice and informative. I'm going to update my blog post later to link to it if you don't mind.

**Comment by dgriff777** [comment]
Thanks @hardmaru! Yeah its fine to link if you want to. Just updated it to use newly implemented A3C-GPU version. Haven't run it on Bipedal but for Atari still using larger model it converges for PongDeterministic-v4 in 10 minutes on my dgx station (compared to 45mins for CPU version). So should speed up bipedal if you got the gpus. Happy New Year to you as well :)
