### ISSUE TITLE
Solution range?

### ISSUE THREAD

**Issue by MaxwellRebo** [hardmaru/estool#4]
Is there currently a way to set the solution range that the population can search over? For example, for some problems I may wish to bound solutions for each parameter in the (0, 1] range, or (-1, 1).

**Comment by hardmaru** [comment]
If the optimizer provides you with a set of model parameters W, and your evaluation is y = F(W), where y is the metric you are trying to optimize for, you can try doing something like:

y = F(sigmoid(W))
y = F(tanh(W))

or

y = F(clip(W, lo_bound, hi_bound))

**Comment by MaxwellRebo** [comment]
Ok. I'll use scaling functions as needed. Thanks!
